### ISSUE TITLE
The content is empty

### ISSUE THREAD

**Issue by xizeyoupan** [Sija/gitbook2pdf#4]
Hello, I am trying to generate PDFs with your work, but it seems incorrect. How can I solve the problem? Thank you in advance.
```
$ node -v
v18.13.0
$ npm start https://book.2333332.xyz
```
![image](https://user-images.githubusercontent.com/44920131/228922296-41c8b6f3-375a-483a-ad88-04b0237f70c2.png)

**Comment by Sija** [comment]
Running the above command gives me (index.pdf):

<img width="956" alt="image" src="https://user-images.githubusercontent.com/988/228925212-adc2e5fa-5471-4e6b-9953-c982124c6aaa.png">

**Comment by xizeyoupan** [comment]
This bug is related to firefox nightly, though I have no idea why you cannot reproduce.

https://user-images.githubusercontent.com/44920131/229155329-277e4e42-21fa-4663-9e2e-95fe38cecce4.mp4

link above:
- https://redspider.gitbook.io/concurrent/
- https://glysns.gitbook.io/java-basico/

When we run `PUPPETEER_PRODUCT=firefox npm i`, it will install newest version of firefox nightly(113.0a1), which is broken on both windows and linux. I've also tested 110.0a1 (2023-01-10) (64-bit) on windows, and it works well. Normal firefox works well, too.

Adding the launch option `executablePath: 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'` can solve.

**Comment by Sija** [comment]
Seems like it's not something we can fix. Probably it will get fixed in the next Firefox version. As noted in the puppeteer [docs](https://pptr.dev/faq#q-which-firefox-version-does-puppeteer-use) the Firefox nightly version is being used and there doesn't seem to be any way to control this behavior.

Closing, since there's nothing actionable on our side.
